### ISSUE TITLE
add spell-checker helper, and possibly CI test

### ISSUE THREAD

**Issue by ffromani** [openshift-kni/numaresources-operator#495]
add script helper which checks the spelling in the source code, like other projects (k8s comes to mind) do.
Evaluate if this check should be added to CI blocking lanes.

**Comment by jlojosnegros** [comment]
Would https://github.com/openshift/cluster-node-tuning-operator/pull/680 be a good way to solve this issue? 
It would add spellcheck among other checks.

**Comment by ffromani** [comment]
yes, that could be a good way to address this issue

**Comment by danielmellado** [comment]
@jlojosnegros happy to have a chat with you about that if you'd like to.
