### ISSUE TITLE
better handling of NRT Attributes in the e2e suite

### ISSUE THREAD

**Issue by ffromani** [openshift-kni/numaresources-operator#609]
The e2e suite currently:

- [doesn't check top-level Attributes when checking for NRT mutations](https://github.com/openshift-kni/numaresources-operator/pull/608#discussion_r1236804230)
- uses the deprecated `topologyPolicies` field as deciding factor, while it should fetch the same information from the `Attributes`

we need to improve how we handle Attributes in the test suite to fix both cases

**Comment by jlojosnegros** [comment]
I think this have been fixed by #652 
WDYT @ffromani ?

**Comment by ffromani** [comment]
yep, it seem the case.

**Comment by ffromani** [comment]
... except for this part, which needs to be checked

The e2e suite currently:

    https://github.com/openshift-kni/numaresources-operator/pull/608#discussion_r1236804230
